services:
 - name: docker:dind
   command: ["--tls=false"]
variables:
 DOCKER_HOST: "tcp://docker:2375"
 DOCKER_TLS_CERTDIR: ""
 DOCKER_DRIVER: overlay2

stages:
  - compile
  - test
  - build

maven-compile-job:
  image: maven:latest
  stage: compile
  script:
    - mvn compile

maven-test-job:
  image: maven:latest
  stage: test
  script:
    - mvn test

maven-build-job:
  image: maven:latest
  before_script:
    - docker run --privileged -d --name dind-test docker:dind
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar