variables:
  DOCKER_DRIVER: overlay2

stages:
  - compile
  - test
  - build

maven-compile-job:
  image: maven:latest
  stage: compile
  script:
    - mvn compile

maven-build-job:
  image: maven:latest
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar