CREATE SCHEMA IF NOT EXISTS HOGWARTS;
SET search_path TO HOGWARTS, public;

CREATE TABLE IF NOT EXISTS HOGWARTS.ROLE (
ID BIGSERIAL PRIMARY KEY,
NAME TEXT
);

CREATE TABLE IF NOT EXISTS HOGWARTS.GROUP (
ID BIGSERIAL PRIMARY KEY,
NAME TEXT
);

CREATE TABLE IF NOT EXISTS HOGWARTS.LESSON_START_END_TIME (
ID BIGINT PRIMARY KEY,
START_TIME TIME,
END_TIME TIME
);

CREATE TABLE IF NOT EXISTS HOGWARTS.CLASSROOM (
ID BIGSERIAL PRIMARY KEY,
NAME TEXT,
DESCRIPTION TEXT
);

CREATE TABLE IF NOT EXISTS HOGWARTS.SUBJECT (
ID BIGSERIAL PRIMARY KEY,
NAME TEXT,
DESCRIPTION TEXT,
PROFESSOR_ID BIGINT,
CLASSROOM_ID BIGINT
);

CREATE TABLE IF NOT EXISTS HOGWARTS.USER (
ID BIGSERIAL PRIMARY KEY,
GROUP_ID BIGINT,
SUBJECT_ID BIGINT,
FIRST_NAME TEXT,
LAST_NAME TEXT
);

CREATE TABLE IF NOT EXISTS HOGWARTS.USER_ROLE (
USER_ID BIGINT,
ROLE_ID BIGINT,
UNIQUE (USER_ID, ROLE_ID)
);

CREATE TABLE IF NOT EXISTS HOGWARTS.LESSON (
ID BIGSERIAL PRIMARY KEY,
LESSON_DATE DATE,
START_END_TIME_ID INT,
SUBJECT_ID BIGINT,
GROUP_ID BIGINT,
UNIQUE (LESSON_DATE, START_END_TIME_ID, GROUP_ID)
);