-- set subject for professor and professor for subject
UPDATE HOGWARTS.SUBJECT
SET PROFESSOR_ID = (SELECT ID FROM HOGWARTS.USER u WHERE u.FIRST_NAME = 'Severus' AND u.LAST_NAME = 'Snape')
WHERE NAME = 'Potions';

UPDATE HOGWARTS.SUBJECT
SET PROFESSOR_ID = (SELECT ID FROM HOGWARTS.USER u WHERE u.FIRST_NAME = 'Rubeus' AND u.LAST_NAME = 'Hagrid')
WHERE NAME = 'Care of Magical Creatures';

UPDATE HOGWARTS.SUBJECT
SET PROFESSOR_ID = (SELECT ID FROM HOGWARTS.USER u WHERE u.FIRST_NAME = 'Remus' AND u.LAST_NAME = 'Lupin')
WHERE NAME = 'Defence Against the Dark Arts';

UPDATE HOGWARTS.SUBJECT
SET PROFESSOR_ID = (SELECT ID FROM HOGWARTS.USER u WHERE u.FIRST_NAME = 'Pomona' AND u.LAST_NAME = 'Sprout')
WHERE NAME = 'Herbology';

UPDATE HOGWARTS.SUBJECT
SET PROFESSOR_ID = (SELECT ID FROM HOGWARTS.USER u WHERE u.FIRST_NAME = 'Minerva' AND u.LAST_NAME = 'McGonagall')
WHERE NAME = 'Transfiguration';

UPDATE HOGWARTS.SUBJECT
SET PROFESSOR_ID = (SELECT ID FROM HOGWARTS.USER u WHERE u.FIRST_NAME = 'Luna' AND u.LAST_NAME = 'Scamander')
WHERE NAME = 'Field Studies';

UPDATE HOGWARTS.SUBJECT
SET PROFESSOR_ID = (SELECT ID FROM HOGWARTS.USER u WHERE u.FIRST_NAME = 'Firenze')
WHERE NAME = 'Divination';

UPDATE HOGWARTS.SUBJECT
SET PROFESSOR_ID = (SELECT ID FROM HOGWARTS.USER u WHERE u.FIRST_NAME = 'Filius' AND u.LAST_NAME = 'Flitwick')
WHERE NAME = 'Charms';

UPDATE HOGWARTS.SUBJECT
SET PROFESSOR_ID = (SELECT ID FROM HOGWARTS.USER u WHERE u.FIRST_NAME = 'Elspeth' AND u.LAST_NAME = 'MacGillony')
WHERE NAME = 'Study of Ancient Runes';

UPDATE HOGWARTS.SUBJECT
SET PROFESSOR_ID = (SELECT ID FROM HOGWARTS.USER u WHERE u.FIRST_NAME = 'Rolanda' AND u.LAST_NAME = 'Hooch')
WHERE NAME = 'Flying';

UPDATE HOGWARTS.SUBJECT
SET PROFESSOR_ID = (SELECT ID FROM HOGWARTS.USER u WHERE u.FIRST_NAME = 'Jakub' AND u.LAST_NAME = 'Gorski')
WHERE NAME = 'History of Magic';

UPDATE HOGWARTS.SUBJECT
SET PROFESSOR_ID = (SELECT ID FROM HOGWARTS.USER u WHERE u.FIRST_NAME = 'Septima' AND u.LAST_NAME = 'Vector')
WHERE NAME = 'Arithmancy';

-- assign students to group

UPDATE HOGWARTS.USER
SET GROUP_ID = (SELECT ID FROM HOGWARTS.GROUP WHERE NAME = 'Gryffindor-7')
WHERE FIRST_NAME = 'Harry'
  AND LAST_NAME = 'Potter';

UPDATE HOGWARTS.USER
SET GROUP_ID = (SELECT ID FROM HOGWARTS.GROUP WHERE NAME = 'Gryffindor-7')
WHERE FIRST_NAME = 'Hermione'
  AND LAST_NAME = 'Granger';

UPDATE HOGWARTS.USER
SET GROUP_ID = (SELECT ID FROM HOGWARTS.GROUP WHERE NAME = 'Gryffindor-7')
WHERE FIRST_NAME = 'Neville'
  AND LAST_NAME = 'Longbottom';

UPDATE HOGWARTS.USER
SET GROUP_ID = (SELECT ID FROM HOGWARTS.GROUP WHERE NAME = 'Gryffindor-7')
WHERE FIRST_NAME = 'Ronald'
  AND LAST_NAME = 'Weasley';

UPDATE HOGWARTS.USER
SET GROUP_ID = (SELECT ID FROM HOGWARTS.GROUP WHERE NAME = 'Gryffindor-7')
WHERE FIRST_NAME = 'Lavender'
  AND LAST_NAME = 'Brown';

UPDATE HOGWARTS.USER
SET GROUP_ID = (SELECT ID FROM HOGWARTS.GROUP WHERE NAME = 'Gryffindor-7')
WHERE FIRST_NAME = 'Dean'
  AND LAST_NAME = 'Thomas';

UPDATE HOGWARTS.USER
SET GROUP_ID = (SELECT ID FROM HOGWARTS.GROUP WHERE NAME = 'Gryffindor-7')
WHERE FIRST_NAME = 'Seamus'
  AND LAST_NAME = 'Finnigan';

UPDATE HOGWARTS.USER
SET GROUP_ID = (SELECT ID FROM HOGWARTS.GROUP WHERE NAME = 'Gryffindor-7')
WHERE FIRST_NAME = 'Parvati'
  AND LAST_NAME = 'Patil';

-- assign subject to classroom

UPDATE HOGWARTS.SUBJECT s
SET CLASSROOM_ID = (SELECT ID FROM HOGWARTS.CLASSROOM c WHERE c.NAME = 'Potions Classroom')
WHERE s.NAME = 'Potions';

UPDATE HOGWARTS.SUBJECT s
SET CLASSROOM_ID = (SELECT ID FROM HOGWARTS.CLASSROOM c WHERE c.NAME = 'Hagrid''s Hut')
WHERE s.NAME = 'Care of Magical Creatures';

UPDATE HOGWARTS.SUBJECT s
SET CLASSROOM_ID = (SELECT ID FROM HOGWARTS.CLASSROOM c WHERE c.NAME = 'Classroom 3C')
WHERE s.NAME = 'Defence Against the Dark Arts';

UPDATE HOGWARTS.SUBJECT s
SET CLASSROOM_ID = (SELECT ID FROM HOGWARTS.CLASSROOM c WHERE c.NAME = 'Class 102')
WHERE s.NAME = 'Herbology';

UPDATE HOGWARTS.SUBJECT s
SET CLASSROOM_ID = (SELECT ID FROM HOGWARTS.CLASSROOM c WHERE c.NAME = 'Class 34')
WHERE s.NAME = 'Transfiguration';

UPDATE HOGWARTS.SUBJECT s
SET CLASSROOM_ID = (SELECT ID FROM HOGWARTS.CLASSROOM c WHERE c.NAME = 'Forbidden Forest')
WHERE s.NAME = 'Field Studies';

UPDATE HOGWARTS.SUBJECT s
SET CLASSROOM_ID = (SELECT ID FROM HOGWARTS.CLASSROOM c WHERE c.NAME = 'Divination Classroom')
WHERE s.NAME = 'Divination';

UPDATE HOGWARTS.SUBJECT s
SET CLASSROOM_ID = (SELECT ID FROM HOGWARTS.CLASSROOM c WHERE c.NAME = 'Classroom 2E')
WHERE s.NAME = 'Charms';

UPDATE HOGWARTS.SUBJECT s
SET CLASSROOM_ID = (SELECT ID FROM HOGWARTS.CLASSROOM c WHERE c.NAME = 'Classroom 6A')
WHERE s.NAME = 'Study of Ancient Runes';

UPDATE HOGWARTS.SUBJECT s
SET CLASSROOM_ID = (SELECT ID FROM HOGWARTS.CLASSROOM c WHERE c.NAME = 'Backyard')
WHERE s.NAME = 'Flying';

UPDATE HOGWARTS.SUBJECT s
SET CLASSROOM_ID = (SELECT ID FROM HOGWARTS.CLASSROOM c WHERE c.NAME = 'Classroom 4F')
WHERE s.NAME = 'History of Magic';

UPDATE HOGWARTS.SUBJECT s
SET CLASSROOM_ID = (SELECT ID FROM HOGWARTS.CLASSROOM c WHERE c.NAME = 'Classroom 7A')
WHERE s.NAME = 'Arithmancy';