INSERT INTO HOGWARTS.LESSON (LESSON_DATE, START_END_TIME_ID, SUBJECT_ID, GROUP_ID)
SELECT '2023-09-04', 1, s.ID, g.ID
FROM HOGWARTS.SUBJECT s
         CROSS JOIN HOGWARTS.GROUP g
WHERE s.NAME = 'Potions'
  AND g.NAME = 'Gryffindor-7';

INSERT INTO HOGWARTS.LESSON (LESSON_DATE, START_END_TIME_ID, SUBJECT_ID, GROUP_ID)
SELECT '2023-09-04', 2, s.ID, g.ID
FROM HOGWARTS.SUBJECT s
         CROSS JOIN HOGWARTS.GROUP g
WHERE s.NAME = 'History of Magic'
  AND g.NAME = 'Gryffindor-7';

INSERT INTO HOGWARTS.LESSON (LESSON_DATE, START_END_TIME_ID, SUBJECT_ID, GROUP_ID)
SELECT '2023-09-04', 3, s.ID, g.ID
FROM HOGWARTS.SUBJECT s
         CROSS JOIN HOGWARTS.GROUP g
WHERE s.NAME = 'Care of Magical Creatures'
  AND g.NAME = 'Gryffindor-7';

INSERT INTO HOGWARTS.LESSON (LESSON_DATE, START_END_TIME_ID, SUBJECT_ID, GROUP_ID)
SELECT '2023-09-04', 4, s.ID, g.ID
FROM HOGWARTS.SUBJECT s
         CROSS JOIN HOGWARTS.GROUP g
WHERE s.NAME = 'Defence Against the Dark Arts'
  AND g.NAME = 'Gryffindor-7';

INSERT INTO HOGWARTS.LESSON (LESSON_DATE, START_END_TIME_ID, SUBJECT_ID, GROUP_ID)
SELECT '2023-09-04', 5, s.ID, g.ID
FROM HOGWARTS.SUBJECT s
         CROSS JOIN HOGWARTS.GROUP g
WHERE s.NAME = 'Field Studies'
  AND g.NAME = 'Gryffindor-7';