ALTER TABLE hogwarts.lesson
    DROP CONSTRAINT subject_id_fk;
ALTER TABLE hogwarts.lesson
    ADD CONSTRAINT SUBJECT_ID_FK FOREIGN KEY (SUBJECT_ID) REFERENCES HOGWARTS.SUBJECT (ID) ON DELETE CASCADE;

ALTER TABLE hogwarts.lesson
    DROP CONSTRAINT group_id_fk;
ALTER TABLE hogwarts.lesson
    ADD CONSTRAINT GROUP_ID_FK FOREIGN KEY (GROUP_ID) REFERENCES HOGWARTS.GROUP (ID) ON DELETE CASCADE;